#   CREATE DATABASE
CREATE DATABASE ACADEMIX;

#   USER ADMIN
CREATE USER 'Academix_Admin'@'%';
GRANT USAGE ON *.* TO 'Academix_Admin'@'%' 
REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER ON `academix`.* TO 'Academix_Admin'@'%' WITH GRANT OPTION;


#
#   CREATE COMMON TABLES
#

CREATE TABLE ACADEMIX.USERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(10) NOT NULL UNIQUE,
    PASS_HASH CHAR(64) NOT NULL
);

CREATE TABLE ACADEMIX.SESSION(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER INT NOT NULL REFERENCES USERS(ID),
    DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOKEN VARCHAR(64) NOT NULL UNIQUE,
    EXPIRY TIMESTAMP NOT NULL DEFAULT DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 1 WEEK)
);

CREATE TABLE ACADEMIX.DEPARTMENTS(
    CODE VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE ACADEMIX.TEACHERS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TEACHER INT NOT NULL REFERENCES USERS(ID),
    APPROVER VARCHAR(100) NOT NULL REFERENCES USERS(ID),
    STATUS BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE ACADEMIX.SUBJECTS(
    CODE VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(10) NOT NULL REFERENCES DEPARTMENTS(CODE),
    TEACHER INT REFERENCES TEACHERS(ID)
);

CREATE TABLE ACADEMIX.STUDENTS(
    USN VARCHAR(12) PRIMARY KEY,
    STUDENT INT NOT NULL REFERENCES USERS(ID),
    DEPARTMENT VARCHAR(10) NOT NULL REFERENCES DEPARTMENTS(CODE),
    BATCH VARCHAR(10) NOT NULL,
    APPROVER VARCHAR(100) NOT NULL REFERENCES USERS(ID),
    STATUS BOOLEAN NOT NULL DEFAULT FALSE
);

#
#   ROLES AND AUTHORIZATION
#

CREATE TABLE ACADEMIX.ROLES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE ACADEMIX.PERMISSIONS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE ACADEMIX.ROLES_PERMISSIONS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE INT NOT NULL REFERENCES ROLES(ID),
    PERMISSION INT NOT NULL REFERENCES PERMISSIONS(ID),
    LEVEL TINYINT NOT NULL CHECK (LEVEL>0 AND LEVEL<3)
);

CREATE TABLE ACADEMIX.AUTHORIZATION(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER INT NOT NULL REFERENCES USERS(ID),
    ROLE INT NOT NULL REFERENCES ROLES(ID),
    APPROVER VARCHAR(100) NOT NULL REFERENCES USERS(EMAIL),
    STATUS CHAR(1) NOT NULL DEFAULT "P" CHECK(STATUS IN ("A", "D", "P"))
);

#
#   SKILLS
#

CREATE TABLE ACADEMIX.SKILLSET(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL
);

CREATE TABLE ACADEMIX.SKILLS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SKILLSET INT NOT NULL REFERENCES SKILLSET(ID),    
    NAME VARCHAR(50) NOT NULL,
    LINK VARCHAR(2083) NOT NULL
);

CREATE TABLE ACADEMIX.STUDENT_SKILLS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT VARCHAR(12) NOT NULL REFERENCES STUDENTS(ID),
    SKILLS INT NOT NULL REFERENCES SKILLS(ID)
);

#
#   PROGRESS
#

CREATE TABLE ACADEMIX.PROJECT(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    MANAGER INT NOT NULL REFERENCES USERS(ID),
    TEAMLEAD VARCHAR(12) NOT NULL REFERENCES STUDENTS(ID),
    MEMBER1 VARCHAR(12) REFERENCES STUDENTS(ID),
    MEMBER2 VARCHAR(12) REFERENCES STUDENTS(ID),
    MEMBER3 VARCHAR(12) REFERENCES STUDENTS(ID),
    COORDINATOR VARCHAR(100) NOT NULL REFERENCES USERS(EMAIL)
);

CREATE TABLE ACADEMIX.PROJECT_PHASES(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PROJECT INT REFERENCES PROGRESS(ID),
    PHASE_NAME VARCHAR(20) NOT NULL,
    DUE_DATE DATE NOT NULL,
    FILES VARCHAR(2083),
    STATUS BOOLEAN NOT NULL DEFAULT FALSE,
    COORDINATOR_STATUS BOOLEAN NOT NULL DEFAULT FALSE
);

#
#   OTHER FUNCTIONALITIES
#

CREATE TABLE ACADEMIX.ACADEMIC(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT INT NOT NULL REFERENCES STUDENTS(ID),
    SUBJECT VARCHAR(10) NOT NULL REFERENCES SUBJECTS(CODE),
    MARKS INT NOT NULL REFERENCES MARKS
);

CREATE TABLE ACADEMIX.MARKS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SUBJECT CODE VARCHAR(10) REFERENCES SUBJECTS(CODE),
    IA1 INT,
    IA2 INT,
    EXTERNAL INT,
    LAB INT
);

#
#   FACIAL RECOGNITION ATTENDANCE
#
CREATE TABLE ACADEMIX.MODEL(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USN VARCHAR(12) NOT NULL REFERENCES STUDENTS(USN),
    IMAGE MEDIUMBLOB NOT NULL
);

CREATE TABLE ACADEMIX.ATTENDANCE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT VARCHAR(12) NOT NULL REFERENCES STUDENTS(USN),
    ATTMOD INT NOT NULL REFERENCES USERS(ID),
    SUBJECT VARCHAR(10) NOT NULL REFERENCES SUBJECTS(CODE),
    DATETIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

#
#   EXPIRED_SESSIONS EVENT
#

CREATE EVENT EXPIRED_SESSIONS
ON SCHEDULE 
    EVERY 1 DAY
    STARTS '2024-12-15 00:15:00'   
DO
    DELETE FROM SESSION WHERE EXPIRY < NOW();


#
#   DATA ENTRY
#

INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('', '');
INSERT INTO ROLES(NAME) VALUES('');
INSERT INTO PERMISSIONS(NAME) VALUES ('');
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (, '', , );
INSERT INTO AUTHORIZATION(USER, ROLE, APPROVER, STATUS) VALUES (, '', );
INSERT INTO SUBJECTS(CODE, NAME, DEPARTMENT, TEACHER) VALUES ('', '', '', );
INSERT INTO SKILLSET(NAME) VALUES('');
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(, '', '')


#   ROLES DATA
INSERT INTO ROLES(NAME) VALUES('ADMIN');
INSERT INTO ROLES(NAME) VALUES('PRINCIPAL');
INSERT INTO ROLES(NAME) VALUES('HOD');
INSERT INTO ROLES(NAME) VALUES('COORDINATOR');
INSERT INTO ROLES(NAME) VALUES('PROFESSOR');
INSERT INTO ROLES(NAME) VALUES('STAFF');
INSERT INTO ROLES(NAME) VALUES('OFFICE');
INSERT INTO ROLES(NAME) VALUES('ATTMOD');
INSERT INTO ROLES(NAME) VALUES('STUDENT');
INSERT INTO ROLES(NAME) VALUES('GUEST');
INSERT INTO ROLES(NAME) VALUES('SERVICE');

#   PERMISSIONS DATA
INSERT INTO PERMISSIONS(NAME) VALUES ("department");
INSERT INTO PERMISSIONS(NAME) VALUES ("subject");
INSERT INTO PERMISSIONS(NAME) VALUES ("role");
INSERT INTO PERMISSIONS(NAME) VALUES ("permission");
INSERT INTO PERMISSIONS(NAME) VALUES ("project");
INSERT INTO PERMISSIONS(NAME) VALUES ("skillset");
INSERT INTO PERMISSIONS(NAME) VALUES ("skill");
INSERT INTO PERMISSIONS(NAME) VALUES ("approver_1");
INSERT INTO PERMISSIONS(NAME) VALUES ("approver_2");
INSERT INTO PERMISSIONS(NAME) VALUES ("approver_3");
INSERT INTO PERMISSIONS(NAME) VALUES ("approver_4");

#   ROLES_PERMISSIONS DATA
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 1, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 2, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 3, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 4, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 5, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 6, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 7, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 8, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 9, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 10, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (1, 11, 2);

INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 2, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 5, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 6, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 7, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 10, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 8, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (3, 9, 2);

INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (11, 9, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (11, 5, 2);
INSERT INTO ROLES_PERMISSIONS(ROLE, PERMISSION, LEVEL) VALUES (11, 7, 2);

#   DEPARTMENTS DATA
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('CS', 'Computer Science and Engg');
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('AI', 'Artificial Intelligence');
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('DS', 'Data Science');
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('ME', 'Mechanical Engineering');
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('EC', 'Electronic and Communication');
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('EE', 'Electrical and Electronics');
INSERT INTO DEPARTMENTS(CODE, NAME) VALUES('CE', 'Civil Engineering');

#   AUTH DATA
INSERT INTO AUTHORIZATION(USER, ROLE, APPROVER, STATUS) VALUES (1, 1, 'admin@admin.com', 'A');
INSERT INTO AUTHORIZATION(USER, ROLE, APPROVER, STATUS) VALUES (3, 3, 'admin@admin.com', 'A');
INSERT INTO AUTHORIZATION(USER, ROLE, APPROVER, STATUS) VALUES (5, 11, 'hod@admin.com', 'A');

#   SKILLSET DATA
INSERT INTO SKILLSET(NAME) VALUES('PROJECT MANAGEMENT');
INSERT INTO SKILLSET(NAME) VALUES('SOFTWARE DEVELOPMENT');
INSERT INTO SKILLSET(NAME) VALUES('CLOUD COMPUTING');
INSERT INTO SKILLSET(NAME) VALUES('DATA ANALYSIS');
INSERT INTO SKILLSET(NAME) VALUES('CYBER SECURITY');
INSERT INTO SKILLSET(NAME) VALUES('MOBILE APP DEVELOPMENT');
INSERT INTO SKILLSET(NAME) VALUES('DATA SCIENCE');
INSERT INTO SKILLSET(NAME) VALUES('WEB DEVELOPMENT');
INSERT INTO SKILLSET(NAME) VALUES('ARTIFICIAL INTELLIGENCE');
INSERT INTO SKILLSET(NAME) VALUES('BASIC IT SKILLS');
INSERT INTO SKILLSET(NAME) VALUES('DATA MANAGEMENT');

#   SKILLS DATA
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(1, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(1, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(1, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(1, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(1, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(1, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')
INSERT INTO SKILLS(SKILLSET, NAME, LINK) VALUES(2, '', '')



#   SUBJECTS DATA
INSERT INTO SUBJECTS(CODE, NAME, DEPARTMENT, TEACHER) VALUES ('BCS501', 'SEPM', 'CS', 1);
INSERT INTO SUBJECTS(CODE, NAME, DEPARTMENT, TEACHER) VALUES ('BCS502', 'TOC', 'CS', );
